services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./backend/package.json:/app/package.json:rw
      - ./backend/.env:/app/.env:rw
      # - ./backend/jest.config.js:/app/jest.config.js
      - ./backend:/app
  #   environment:
  #     - WATCHPACK_POLLING=true
  #   depends_on:
  #     db:
  #       condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app

  # db:
  #   image: postgres:16
  #   container_name: portfolio-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: db_portfolio
  #     POSTGRES_USER: portfolio
  #     POSTGRES_PASSWORD: portfolio
  #   volumes:
  #     - ./dbData:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -d db_portfolio -U portfolio"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
